title: My First Blog
author: Chuck B
email: ecb.chuck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am updating this yaml file in hopes to understand this better.
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
